### ISSUE TITLE
为什么没有放在graph.ndata中？

### ISSUE THREAD

**Issue by DawnyWu** [dglai/maxp_baseline_model#1]
我看到dgl的dataset一般把数据，标签，mask放在graph.ndata中。
在baseline代码里数据，标签，mask分开的，这是什么原因呢？
是不是放在ndata里会出问题啊？

**Comment by zhjwy9343** [comment]
谢谢，这里我只是按照比赛的数据分开处理，方便对DGL不熟悉的用户来了解这些都是怎么产生的。

把mask放到graph.ndata不会有问题。如果你熟悉放到graph.ndata里面，可以直接这么做来方便数据存储和处理。
